BaseURL = "https://aarshinkan2020.netlify.app/"

author = "Anti-Aging Record"
paginate = 6
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "AAR 2020新歓特設サイト"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""
disqusShortname=""
copyright = "&copy;Anti-Aging Record 2009-2020"
sectionPagesMenu = "main"

[params]
description = "Anti-Aging Record 2020新歓特設サイト"
twitter = "antiagingrecord"
useIcon = true 
useTwitterCard = true
# exampleSite must not have js share widget: #36
# shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
shareTo = ["Twitter"]
showFooterCredits = true
math = true

[taxonomies]
author = "authors"
tags = "tags"
categories = "categories"

[menu]
    [[menu.main]]
        identifier = "activity"
        name = "活動紹介"
        pre = "<i class='fas fa-info-circle'></i>"
        url = "/activity/"
        weight=3

    [[menu.main]]
        identifier = "remixcompilation"
        pre = "<i class='fas fa-download'></i>"
        name = "Remixコンピ"
        url = "/remixcompilation2020/"

    [[menu.main]]
        identifier = "member"
        name = "メンバー"
        pre = "<i class='fas fa-users'></i>"
        url = "/member/"

    [[menu.main]]
        identifier = "kouza"
        pre = "🔰"
        name = "初めてのDTM"
        url = "/kouza/"
        hasChildren = true
                
    [[menu.main]]
        parent = "kouza"
        name = "DTM講座記事一覧"
        url = "/kouza/"
        weight=20

    [[menu.main]]
        parent = "kouza"
        name = "DAWについて"
        url = "/kouza/dawintroduction"
        weight=22

    [[menu.main]]
        parent = "kouza"
        name = "DTMについて"
        url = "/kouza/dtmintroduction"
        weight=21